RECENTLY_VOCALO_TABLE_NAME = "recently_famous_vocalovideos"
RECENTLY_UTATTEMIATA_TABLE_NAME = "recently_famous_utattemita"
FAMOUS_VOCALO_TABLE_NAME = "famous_vocalovideos"
NOT_VOCALO_TABLE_NAME = "not_vocalovideos"
MAIL_USER_TABLE_NAME = "mail_users"